import React, { useMemo } from "react";
import type { HomeAssistant, HassEntity } from "../types";
import { HACardHost } from "./HACardHost";

type Widget = { id: string; widgetType: string; entityIds: string[]; size: string; settings?: Record<string, unknown> };
const labels: Record<string, string> = { "light.collection":"תאורה","climate.thermostat":"אקלים","media.player":"מדיה","camera.viewer":"מצלמה","cover.control":"פתחים","fan.control":"מאוורר","switch.collection":"מתגים","security.lock":"מנעול","security.alarm":"אזעקה","sensor.temperature":"טמפרטורה","sensor.humidity":"לחות","sensor.power":"הספק","sensor.energy":"אנרגיה","sensor.value":"חיישן","binary_sensor.status":"מצב","person.presence":"נוכחות","weather.forecast":"מזג אוויר","entity.generic":"ישויות" };
const entityName = (entity?: HassEntity) => String(entity?.attributes.friendly_name ?? entity?.entity_id.split(".")[1]?.replaceAll("_", " ") ?? "ישות");
const inactive = new Set(["off", "unavailable", "unknown", "idle", "not_home", "closed"]);

export function RuntimeWidget({ widget, hass, onFeedback }: { widget: Widget; hass: HomeAssistant; onFeedback: (message: string) => void }) {
  const entities = useMemo(() => widget.entityIds.map((id) => hass.states[id]).filter(Boolean), [widget.entityIds, hass.states]);
  const primary = entities[0];
  const active = entities.filter((entity) => !inactive.has(entity.state)).length;
  async function toggle(entity: HassEntity) { await hass.callService("homeassistant", "toggle", {}, { entity_id: entity.entity_id }); onFeedback(`${entityName(entity)} · הפעולה נשלחה`); }
  async function climateStep(delta: number) { if (!primary) return; const target=Number(primary.attributes.temperature ?? primary.attributes.target_temp_high ?? 24); await hass.callService("climate","set_temperature",{temperature:target+delta},{entity_id:primary.entity_id}); onFeedback(`טמפרטורת היעד ${target+delta}°`); }

  if (widget.widgetType === "legacy.lovelace-card" && widget.settings?.source && typeof widget.settings.source === "object") {
    const source = widget.settings.source as Record<string, unknown>;
    const config = source.type === "entities" ? { ...source, entity: undefined, entities: widget.entityIds } : { ...source, entities: undefined, entity: widget.entityIds[0] ?? source.entity };
    return <HACardHost hass={hass} config={config} />;
  }

  if (widget.widgetType === "climate.thermostat" && primary) {
    const current=Number(primary.attributes.current_temperature ?? 0), target=Number(primary.attributes.temperature ?? primary.attributes.target_temp_high ?? 0), mode=primary.state;
    return <article className={`runtime-widget climate-widget mode-${mode} size-${widget.size}`}><header><div><small>אקלים בחדר</small><h3>{entityName(primary)}</h3></div><span>{mode}</span></header><div className="climate-orbit"><div><small>עכשיו</small><strong>{current.toFixed(1)}°</strong><b>יעד {target.toFixed(1)}°</b></div></div><footer><button onClick={()=>climateStep(.5)}>+</button><span>{String(primary.attributes.hvac_action ?? mode)}</span><button onClick={()=>climateStep(-.5)}>−</button></footer></article>;
  }
  if (widget.widgetType === "camera.viewer" && primary) return <article className={`runtime-widget camera-widget size-${widget.size}`}><img src={`/api/camera_proxy/${primary.entity_id}`} alt={entityName(primary)} loading="lazy"/><header><div><small>מצלמה</small><h3>{entityName(primary)}</h3></div><span>LIVE</span></header></article>;
  if (widget.widgetType === "media.player" && primary) { const playing=primary.state==="playing"; return <article className={`runtime-widget media-widget ${playing?"is-active":""} size-${widget.size}`}><header><div><small>מדיה</small><h3>{entityName(primary)}</h3></div><span>{primary.state}</span></header><div className="media-title"><strong>{String(primary.attributes.media_title ?? "אין תוכן פעיל")}</strong><small>{String(primary.attributes.media_artist ?? primary.attributes.app_name ?? "")}</small></div><footer><button onClick={()=>hass.callService("media_player","media_previous_track",{},{entity_id:primary.entity_id})}>‹</button><button className="media-main" onClick={()=>hass.callService("media_player",playing?"media_pause":"media_play",{},{entity_id:primary.entity_id})}>{playing?"Ⅱ":"▶"}</button><button onClick={()=>hass.callService("media_player","media_next_track",{},{entity_id:primary.entity_id})}>›</button></footer></article>; }
  if (widget.widgetType === "light.collection") return <article className={`runtime-widget collection-widget light-widget ${active?"is-active":""} size-${widget.size}`}><header><div><small>תאורה</small><h3>{active?`${active} מוקדים פעילים`:"כל התאורה כבויה"}</h3></div><span>{entities.length}</span></header><div className="entity-controls">{entities.slice(0,12).map((entity)=>{const on=entity.state==="on",brightness=Math.round(Number(entity.attributes.brightness??0)/2.55),dimmable=Number(entity.attributes.supported_color_modes ? 1 : entity.attributes.supported_features ?? 0)>0;return <div className={`light-row ${on?"active":""}`} key={entity.entity_id}><button onClick={()=>toggle(entity)}><i/><span><strong>{entityName(entity)}</strong><small>{on?`${brightness || 100}%`:"כבוי"}</small></span></button>{dimmable&&<input aria-label={`עוצמת ${entityName(entity)}`} type="range" min="1" max="100" value={on?brightness||100:1} onChange={(event)=>hass.callService("light","turn_on",{brightness_pct:Number(event.target.value)},{entity_id:entity.entity_id})}/>}</div>})}</div></article>;
  if (widget.widgetType === "cover.control" && primary) return <article className={`runtime-widget cover-widget ${primary.state!=="closed"?"is-active":""} size-${widget.size}`}><header><div><small>תריסים ווילונות</small><h3>{entityName(primary)}</h3></div><span>{String(primary.attributes.current_position ?? (primary.state==="open"?100:0))}%</span></header><div className="cover-position"><i style={{height:`${Number(primary.attributes.current_position ?? 0)}%`}}/></div><footer><button onClick={()=>hass.callService("cover","open_cover",{},{entity_id:primary.entity_id})}>פתיחה</button><button onClick={()=>hass.callService("cover","stop_cover",{},{entity_id:primary.entity_id})}>עצירה</button><button onClick={()=>hass.callService("cover","close_cover",{},{entity_id:primary.entity_id})}>סגירה</button></footer></article>;
  if (widget.widgetType === "security.alarm" && primary) return <article className={`runtime-widget alarm-widget state-${primary.state} size-${widget.size}`}><header><div><small>לוח בקרה</small><h3>{entityName(primary)}</h3></div><span>{primary.state}</span></header><div className="alarm-state"><strong>{primary.state==="disarmed"?"המערכת מנוטרלת":"המערכת דרוכה"}</strong></div><footer><button onClick={()=>hass.callService("alarm_control_panel","alarm_disarm",{},{entity_id:primary.entity_id})}>נטרול</button><button onClick={()=>hass.callService("alarm_control_panel","alarm_arm_home",{},{entity_id:primary.entity_id})}>מצב בית</button><button onClick={()=>hass.callService("alarm_control_panel","alarm_arm_away",{},{entity_id:primary.entity_id})}>יציאה</button></footer></article>;
  if (widget.widgetType.startsWith("sensor.") && primary) return <article className={`runtime-widget sensor-widget size-${widget.size}`}><header><div><small>{labels[widget.widgetType]??"חיישן"}</small><h3>{entityName(primary)}</h3></div></header><strong className="sensor-value">{primary.state}<small>{String(primary.attributes.unit_of_measurement??"")}</small></strong></article>;
  return <article className={`runtime-widget collection-widget ${active?"is-active":""} size-${widget.size}`}><header><div><small>{labels[widget.widgetType]??widget.widgetType}</small><h3>{active?`${active} פעילים`:"הכל שקט"}</h3></div><span>{entities.length}</span></header><div className="entity-controls">{entities.slice(0,8).map((entity)=><button className={!inactive.has(entity.state)?"active":""} key={entity.entity_id} onClick={()=>toggle(entity)}><i/><span><strong>{entityName(entity)}</strong><small>{entity.state}</small></span></button>)}</div></article>;
}
