import React, { useEffect, useRef } from "react";
import type { HassEntity, HomeAssistant, LinkConfig } from "../types";

const Icon=({icon}:{icon:string})=>React.createElement("ha-icon",{icon});
const domain=(id:string)=>id.split(".",1)[0];
const name=(state:HassEntity)=>String(state.attributes.friendly_name||state.entity_id);
const valid=(state:HassEntity)=>!["unknown","unavailable"].includes(state.state);
const entities=(hass:HomeAssistant|undefined,domains:string[])=>Object.values(hass?.states||{}).filter((state)=>domains.includes(domain(state.entity_id))&&valid(state));
const moreInfo=(entityId:string)=>window.dispatchEvent(new CustomEvent("hass-more-info",{detail:{entityId},bubbles:true,composed:true}));
const feedback=(message:string,type:"info"|"success"|"error"="info")=>window.dispatchEvent(new CustomEvent("homeii-feedback",{detail:{message,type}}));
async function service(hass:HomeAssistant|undefined,domainName:string,serviceName:string,data:Record<string,unknown>,entityId:string){if(!hass){feedback("אין חיבור ל־Home Assistant","error");return;}feedback("מבצע פעולה…");try{await hass.callService(domainName,serviceName,data,{entity_id:entityId});feedback("הפעולה בוצעה","success");}catch{feedback("הפעולה נכשלה","error");}}

class WidgetBoundary extends React.Component<React.PropsWithChildren,{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}componentDidCatch(error:unknown){console.error("HOMEii widget failed",error)}render(){return this.state.failed?<Empty icon="mdi:alert-circle-outline" text="הרכיב לא הצליח להיטען"/>:this.props.children}}

export function SpecialView({item,hass,legacyDashboardPath,cameraSelection,onHome}:{item:LinkConfig;hass?:HomeAssistant;legacyDashboardPath:string;cameraSelection?:string[]|null;onHome:()=>void}){
  const content=renderContent(item,hass,legacyDashboardPath,cameraSelection);
  return <section className={`special-view special-${item.id}`}>
    <header className="special-header glass"><button className="special-back" onClick={onHome}><Icon icon="mdi:arrow-right"/><span>מסך הבית</span></button><div><small>HOMEii Collection</small><h1>{item.name}</h1></div><span className="special-title-icon"><Icon icon={item.icon}/></span></header>
    <div className="special-content"><WidgetBoundary>{content}</WidgetBoundary></div>
  </section>;
}

function renderContent(item:LinkConfig,hass:HomeAssistant|undefined,legacyPath:string,cameraSelection?:string[]|null){
  if(item.id==="security")return <CameraView hass={hass} cameraSelection={cameraSelection}/>;
  if(item.id==="intercom")return <IntercomView hass={hass}/>;
  if(item.id==="weather")return <WeatherView hass={hass}/>;
  if(item.id==="power")return <LegacyEnergyView item={item} legacyPath={legacyPath}/>;
  if(item.id==="vacuum")return <VacuumView hass={hass}/>;
  if(item.id==="lights")return <LightsView hass={hass}/>;
  if(item.id==="resources")return <ResourcesView hass={hass}/>;
  if(item.id==="media")return <MusicFlow hass={hass}/>;
  if(["media-players","advanced-media"].includes(item.id))return <MediaView hass={hass}/>;
  return <section className="legacy-widget glass"><iframe title={item.name} src={`${legacyPath}/${item.legacyPath}?kiosk`} allow="autoplay; fullscreen; microphone"/></section>;
}

function Empty({icon,text}:{icon:string;text:string}){return <div className="special-empty glass"><Icon icon={icon}/><strong>{text}</strong><small>הכרטיס יופיע אוטומטית כשישות מתאימה תהיה זמינה ב־HA</small></div>}

function CameraView({hass,cameraSelection}:{hass?:HomeAssistant;cameraSelection?:string[]|null}){const preferred=["camera.intercom","camera.entrance","camera.a8105_e_0"];const automatic=entities(hass,["camera"]);const discovered=[...preferred.filter((id)=>hass?.states[id]),...automatic.map((state)=>state.entity_id).filter((id)=>!preferred.includes(id))];const list=cameraSelection===null||cameraSelection===undefined?discovered:cameraSelection.filter((id)=>hass?.states[id]);if(!list.length)return <Empty icon="mdi:cctv" text="לא נבחרו מצלמות להצגה"/>;return <div className="camera-grid">{list.map((entityId)=><AdvancedCamera key={entityId} entityId={entityId} hass={hass}/>)}</div>}

function AdvancedCamera({entityId,hass}:{entityId:string;hass?:HomeAssistant}){const host=useRef<HTMLElement|null>(null);useEffect(()=>{let disposed=false;customElements.whenDefined("advanced-camera-card").then(()=>{if(disposed)return;const card=host.current as (HTMLElement&{hass?:HomeAssistant;setConfig?:(config:Record<string,unknown>)=>void})|null;if(!card)return;card.setConfig?.({type:"custom:advanced-camera-card",cameras:[{camera_entity:entityId,live_provider:"go2rtc",go2rtc:{modes:["webrtc","mse"]}}],view:{default:"live"},menu:{style:"outside",position:"bottom"},live:{auto_play:["visible","selected"]}});card.hass=hass;});return()=>{disposed=true};},[entityId,hass]);return <article className="camera-card advanced-camera-shell glass">{React.createElement("advanced-camera-card",{ref:host})}</article>}

function WeatherView({hass}:{hass?:HomeAssistant}){const state=entities(hass,["weather"])[0];if(!state)return <Empty icon="mdi:weather-partly-cloudy" text="אין נתוני מזג אוויר"/>;const forecast=Array.isArray(state.attributes.forecast)?state.attributes.forecast.slice(0,5) as Array<Record<string,unknown>>:[];return <div className="weather-layout"><article className="weather-now glass"><Icon icon="mdi:weather-partly-cloudy"/><div><small>{name(state)}</small><strong>{String(state.attributes.temperature??"—")}°</strong><span>{state.state}</span></div><dl><div><dt>לחות</dt><dd>{String(state.attributes.humidity??"—")}%</dd></div><div><dt>רוח</dt><dd>{String(state.attributes.wind_speed??"—")}</dd></div></dl></article><section className="forecast-strip glass">{forecast.length?forecast.map((day,index)=><article key={index}><small>{new Date(String(day.datetime)).toLocaleDateString("he-IL",{weekday:"short"})}</small><Icon icon="mdi:weather-partly-cloudy"/><strong>{String(day.temperature??"—")}°</strong></article>):<span>תחזית תוצג כאשר האינטגרציה תספק נתונים</span>}</section></div>}

function LegacyEnergyView({item,legacyPath}:{item:LinkConfig;legacyPath:string}){return <section className="legacy-widget energy-legacy glass"><iframe title={item.name} src={`${legacyPath}/${item.legacyPath}?kiosk`} allow="fullscreen"/></section>}

function MusicFlow({hass}:{hass?:HomeAssistant}){
  const host=useRef<HTMLElement|null>(null);
  useEffect(()=>{const element=host.current as (HTMLElement&{hass?:HomeAssistant;setConfig?:(config:Record<string,unknown>)=>void})|null;if(!element)return;element.hass=hass;element.setConfig?.({type:"custom:homeii-music-flow",rtl:true,language:"he",show_ma_button:false,ma_interface_url:"/d5369777_music_assistant_beta",music_assistant_timeout_ms:12000,homeii_engine_mode:"required",discovery_mode_enabled:true,player_sort_mode:"custom",player_order_entities:["media_player.computer_2","media_player.bedroom_2","media_player.bathroom_2","media_player.kitchen_2","media_player.livingroom_2"],use_mass_queue_send_command:true,mobile_liked_mode:"ma",screensaver_controls_enabled:true});},[hass]);
  return <section className="music-flow-host glass"><div className="music-flow-intro"><span><Icon icon="mdi:waveform"/></span><div><small>HOMEii</small><strong>MUSIC FLOW</strong></div><i/></div>{React.createElement("homeii-music-flow",{ref:host})}</section>;
}

function VacuumView({hass}:{hass?:HomeAssistant}){const list=entities(hass,["vacuum"]);if(!list.length)return <Empty icon="mdi:robot-vacuum" text="לא נמצא שואב"/>;return <div className="device-widget-grid">{list.map((state)=>{const active=["cleaning","returning"].includes(state.state);return <article className={`vacuum-widget glass ${active?"active":""}`} key={state.entity_id}><div className="vacuum-orbit"><Icon icon="mdi:robot-vacuum"/><i/></div><h2>{name(state)}</h2><p>{active?"מנקה עכשיו":state.state==="docked"?"בעמדת הטעינה":state.state}</p><div className="widget-actions"><button onClick={()=>service(hass,"vacuum","start",{},state.entity_id)}><Icon icon="mdi:play"/>ניקוי</button><button onClick={()=>service(hass,"vacuum","pause",{},state.entity_id)}><Icon icon="mdi:pause"/>השהיה</button><button onClick={()=>service(hass,"vacuum","return_to_base",{},state.entity_id)}><Icon icon="mdi:home-map-marker"/>חזרה</button></div></article>})}</div>}

function LightsView({hass}:{hass?:HomeAssistant}){const list=entities(hass,["light"]);if(!list.length)return <Empty icon="mdi:lightbulb-group" text="לא נמצאה תאורה"/>;return <div className="special-entity-grid">{list.map((state)=>{const on=state.state==="on",brightness=Math.round(Number(state.attributes.brightness||0)/2.55);return <article className={`entity-widget glass ${on?"active":""}`} key={state.entity_id}><button className="entity-main" onClick={()=>service(hass,"light",on?"turn_off":"turn_on",{},state.entity_id)}><span><Icon icon="mdi:lightbulb"/></span><div><strong>{name(state)}</strong><small>{on?`${brightness||100}% · דולקת`:"כבויה"}</small></div><i/></button>{on&&state.attributes.brightness!==undefined&&<input aria-label={`עוצמת ${name(state)}`} type="range" min="1" max="100" value={brightness||1} onChange={(event)=>service(hass,"light","turn_on",{brightness_pct:Number(event.target.value)},state.entity_id)}/>}</article>})}</div>}

function MediaView({hass}:{hass?:HomeAssistant}){const list=entities(hass,["media_player"]);if(!list.length)return <Empty icon="mdi:speaker-multiple" text="לא נמצאו נגני מדיה"/>;return <div className="media-widget-grid">{list.map((state)=>{const playing=state.state==="playing";return <article className={`media-widget glass ${playing?"active":""}`} key={state.entity_id}><div className="media-cover" style={state.attributes.entity_picture?{backgroundImage:`url(${String(state.attributes.entity_picture)})`}:undefined}><Icon icon="mdi:music-note"/></div><div className="media-meta"><small>{name(state)}</small><strong>{String(state.attributes.media_title||state.state)}</strong><span>{String(state.attributes.media_artist||"")}</span></div><div className="media-buttons"><button onClick={()=>service(hass,"media_player","media_previous_track",{},state.entity_id)}><Icon icon="mdi:skip-previous"/></button><button className="primary" onClick={()=>service(hass,"media_player","media_play_pause",{},state.entity_id)}><Icon icon={playing?"mdi:pause":"mdi:play"}/></button><button onClick={()=>service(hass,"media_player","media_next_track",{},state.entity_id)}><Icon icon="mdi:skip-next"/></button></div></article>})}</div>}

function ResourcesView({hass}:{hass?:HomeAssistant}){const rx=/(processor|memory|disk|cpu|storage|uptime|temperature)/i;const list=entities(hass,["sensor","update"]).filter((s)=>rx.test(`${s.entity_id} ${s.attributes.friendly_name||""} ${s.attributes.device_class||""}`)).slice(0,12);if(!list.length)return <Empty icon="mdi:cpu-64-bit" text="לא נמצאו חיישני מערכת"/>;return <div className="resource-grid">{list.map((state)=><article className="resource-row glass" key={state.entity_id} onClick={()=>moreInfo(state.entity_id)}><Icon icon={domain(state.entity_id)==="update"?"mdi:update":"mdi:memory"}/><div><strong>{name(state)}</strong><small>{domain(state.entity_id)==="update"?"רכיב מערכת":"מדד חי"}</small></div><b>{state.state} {String(state.attributes.unit_of_measurement||"")}</b></article>)}</div>}

function IntercomView({hass}:{hass?:HomeAssistant}){const preferred=["camera.intercom","camera.entrance","sensor.intercom_person_count","binary_sensor.intercom_motion"];const candidates=[...preferred.map((id)=>hass?.states[id]).filter(Boolean) as HassEntity[],...Object.values(hass?.states||{}).filter((s)=>/(doorbell|intercom|כניסה|פעמון)/i.test(`${s.entity_id} ${s.attributes.friendly_name||""}`)&&!preferred.includes(s.entity_id))];const cameras=candidates.filter((s)=>domain(s.entity_id)==="camera");return <div className="intercom-layout">{cameras.length?<CameraView hass={{...hass!,states:Object.fromEntries(cameras.map((s)=>[s.entity_id,s]))}}/>:<Empty icon="mdi:doorbell-video" text="לא נמצאה מצלמת אינטרקום"/>}<div className="resource-grid">{candidates.filter((s)=>domain(s.entity_id)!=="camera").slice(0,8).map((state)=><article className="resource-row glass" key={state.entity_id} onClick={()=>moreInfo(state.entity_id)}><Icon icon="mdi:doorbell-video"/><div><strong>{name(state)}</strong><small>אינטרקום</small></div><b>{state.state}</b></article>)}</div></div>}
